Repository boostcampwm-2024/refactor-web29-honeyflow, pull requests merged in 2025-01, with the labels that each got.

#2 Dockerfile 파일 내 의존성 관련 에러 해결 및 production 단계 최적화
  .dockerignore
  packages/backend/.dockerignore
  packages/backend/Dockerfile
  packages/frontend/.dockerignore
Labels: fix, refactor

#6 리드미 링크 수정
  README.md
Labels: docs

#14 줌 기능에 strategy 패턴 적용
  packages/frontend/eslint.config.js
  packages/frontend/src/hooks/useZoomSpace.ts
  packages/frontend/src/utils/zoomStrategies.ts
Labels: refactor

#13 인터랙션 로직 통합 및 prop 전달 개선
  packages/frontend/src/components/space/SpaceView.tsx
  packages/frontend/src/hooks/useDragNode.ts
  packages/frontend/src/hooks/useMoveNode.ts
  packages/frontend/src/hooks/useSpaceInteractions.ts
Labels: refactor
